-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZtE1Kx9CRzRvJMMd
fztdiyL0wJahLVnMKzPe6yvzSNGgCgYIKoZIzj0DAQehRANCAAQBA/95j8RPkpTq
Fz82Dh1sQE+KRBc+DBABsegP3SJKA/y/rjzCTcgJKmz8C506/Id2YyJm9/IxdwBU
CKG8pQox
-----END PRIVATE KEY-----